#ifndef __QUARD_MBOX_ROUTER_SERVER_ID_H__
#define __QUARD_MBOX_ROUTER_SERVER_ID_H__

#define QUARD_SERVER_ID_MAX 10
#define QUARD_SERVER_ID_LOG 0
#define QUARD_SERVER_ID_VSHELL 1
#define QUARD_SERVER_ID_NOR 2

#endif